// One-off: extract a focused set of common ALLERGENS (drugs, foods, environmental)
// with their UNII codes from the public FDA UNII Names list. We deliberately do NOT
// ship all ~150k substances (77MB, mostly obscure chemicals) — just the ones a
// patient would realistically report as an allergy. Public data, no PHI.
//
// usage: node build-unii.mjs <UNII_Names.txt> <out.ts>
import { readFileSync, writeFileSync } from "node:fs";

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) { console.error("usage: node build-unii.mjs <in.txt> <out.ts>"); process.exit(1); }

// Allergen -> optional lay aliases. We look each up by Display Name / Name.
const ALLERGENS = {
  // antibiotics
  "penicillin g": ["penicillin", "pcn"], "amoxicillin": ["amox"], "ampicillin": [],
  "cephalexin": ["keflex"], "cefdinir": [], "ceftriaxone": [], "azithromycin": ["z-pack", "zithromax"],
  "erythromycin": [], "clindamycin": [], "vancomycin": [], "ciprofloxacin": ["cipro"],
  "levofloxacin": ["levaquin"], "doxycycline": [], "tetracycline": [], "metronidazole": ["flagyl"],
  "nitrofurantoin": ["macrobid"], "sulfamethoxazole": ["sulfa", "bactrim", "septra"], "trimethoprim": [],
  // analgesics / NSAIDs / opioids
  "aspirin": ["asa"], "ibuprofen": ["advil", "motrin"], "naproxen": ["aleve"], "ketorolac": ["toradol"],
  "acetaminophen": ["tylenol", "paracetamol"], "codeine": [], "morphine": [], "hydrocodone": [],
  "oxycodone": [], "tramadol": [], "fentanyl": [], "meperidine": [],
  // other drugs
  "lisinopril": [], "metformin": [], "atorvastatin": [], "gabapentin": [], "phenytoin": ["dilantin"],
  "carbamazepine": [], "lamotrigine": ["lamictal"], "allopurinol": [], "heparin": [], "warfarin": ["coumadin"],
  "insulin": [], "lidocaine": [], "iodine": ["contrast dye", "iodine contrast"], "latex": ["rubber latex"],
  // foods
  "peanut": ["peanuts"], "almond": [], "cashew": [], "walnut": [], "pecan": [], "hazelnut": [],
  "egg": ["eggs"], "soybean": ["soy"], "wheat": ["gluten"], "shrimp": [], "crab": [], "lobster": [],
  "sesame": [], "corn": [], "strawberry": [],
  // environmental / venom
  "nickel": [], "cat dander": ["cats"], "dog dander": ["dogs"], "honey bee venom": ["bee sting", "bee venom"],
};

// build lookup: lower(name) -> {unii, display}; prefer Display Name matches.
const lines = readFileSync(inPath, "utf8").split(/\r?\n/);
const byName = new Map();      // any name -> {unii, display}
for (let i = 1; i < lines.length; i++) {
  const parts = lines[i].split("\t");
  if (parts.length < 4) continue;
  const name = (parts[0] || "").trim().toLowerCase();
  const unii = (parts[2] || "").trim();
  const display = (parts[3] || "").trim();
  if (!unii || !display) continue;
  if (name && !byName.has(name)) byName.set(name, { unii, display });
  const dn = display.toLowerCase();
  if (!byName.has(dn)) byName.set(dn, { unii, display });
}

const entries = [];
const missing = [];
const seen = new Set();
for (const [term, aliases] of Object.entries(ALLERGENS)) {
  const hit = byName.get(term);
  if (!hit) { missing.push(term); continue; }
  if (seen.has(hit.unii)) continue;
  seen.add(hit.unii);
  // description = a clean, human label (the lay term, Title Cased), aliases carry the rest
  const desc = term.replace(/\b\w/g, (c) => c.toUpperCase());
  entries.push({ system: "UNII", code: hit.unii, description: desc, aliases: [hit.display.toLowerCase(), ...aliases] });
}

const js = JSON.stringify(entries);
const ts =
  `// AUTO-GENERATED by scripts/build-unii.mjs from the public FDA UNII Names list.\n` +
  `// Focused common-allergen subset (drugs/foods/environmental), no PHI.\n` +
  `import type { CodeEntry } from "./model";\n` +
  `export const UNII_FULL: CodeEntry[] = JSON.parse(${JSON.stringify(js)});\n`;
writeFileSync(outPath, ts);
console.log(`wrote ${entries.length} allergens -> ${outPath}`);
if (missing.length) console.log(`unresolved (${missing.length}):`, missing.join(", "));
