// One-off: convert the public RxNav allconcepts dump (IN/PIN/BN) into the compact
// JSON-string .ts module Hx's validation pipeline loads. Public RxNorm data (RxCUI
// + name), no UMLS license required (RxNav REST API is open). No PHI.
import { readFileSync, writeFileSync } from "node:fs";

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) {
  console.error("usage: node build-rx.mjs <in.json> <out.ts>");
  process.exit(1);
}

const all = JSON.parse(readFileSync(inPath, "utf8"));
const seen = new Set();
const entries = [];
for (const c of all) {
  const code = String(c.rxcui || "").trim();
  const name = String(c.name || "").trim();
  if (!code || !name) continue;
  if (seen.has(code)) continue; // dedup by RxCUI
  seen.add(code);
  entries.push({ system: "RXNORM", code, description: name });
}

// Stored as a JSON string parsed at runtime (same reason as ICD: avoid a giant
// tuple type from importing a 23k-element .json).
const jsonString = JSON.stringify(entries);
const ts =
  `// AUTO-GENERATED by scripts/build-rx.mjs from the public RxNav allconcepts API\n` +
  `// (term types IN/PIN/BN). Public RxNorm data (RxCUI + name), no license, no PHI.\n` +
  `// Do not edit by hand. Stored as a JSON string parsed at runtime so the TS\n` +
  `// compiler treats it as a single \`string\` (no ${entries.length}-element tuple).\n` +
  `const RAW = ${JSON.stringify(jsonString)};\n` +
  `export const RXNORM_FULL: { system: string; code: string; description: string }[] = JSON.parse(RAW);\n`;
writeFileSync(outPath, ts);
console.log(`wrote ${entries.length} RxNorm codes -> ${outPath}`);
