// One-off: convert the public ICD-10-CM CSV (k4m1113/ICD-10-CSV) into the
// compact JSON shape Hx's validation pipeline loads. Public data, no PHI.
//   input  CSV cols: category, order, codeNoDot, description, descriptionDup, short
//   output JSON:     [{ system:"ICD10", code:"E11.9", description:"..." }, ...]
import { readFileSync, writeFileSync } from "node:fs";

const [, , inPath, outPath] = process.argv;
if (!inPath || !outPath) {
  console.error("usage: node build-icd.mjs <in.csv> <out.json>");
  process.exit(1);
}

// Minimal CSV line parser: handles quoted fields, embedded commas, and "" escapes.
function parseLine(line) {
  const out = [];
  let cur = "";
  let q = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (q) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++; }
        else q = false;
      } else cur += ch;
    } else {
      if (ch === '"') q = true;
      else if (ch === ",") { out.push(cur); cur = ""; }
      else cur += ch;
    }
  }
  out.push(cur);
  return out;
}

// ICD-10-CM display form: decimal point after the 3-char category.
function dot(code) {
  const c = code.trim().toUpperCase();
  return c.length > 3 ? `${c.slice(0, 3)}.${c.slice(3)}` : c;
}

const raw = readFileSync(inPath, "utf8");
const lines = raw.split(/\r?\n/).filter(Boolean);

// stabgan rows wrap the real label as
//   "Header: <cat> - <name> | Specific long description about this code: <DESC>"
// Pull out <DESC>; leave clean rows untouched.
const MARKER = "Specific long description about this code: ";
function cleanDesc(raw) {
  const i = raw.indexOf(MARKER);
  return (i >= 0 ? raw.slice(i + MARKER.length) : raw).trim();
}

// Column layout differs by source: k4m1113 = [cat,order,code,desc,...];
// stabgan = [code,description] with a header row. Detect per-row.
const seen = new Set();
const entries = [];
for (const line of lines) {
  const cols = parseLine(line);
  let code, desc;
  if (cols.length >= 4) {
    code = (cols[2] || "").trim();
    desc = cleanDesc((cols[3] || "").trim());
  } else {
    code = (cols[0] || "").trim();
    desc = cleanDesc((cols[1] || "").trim());
  }
  if (!code || !desc) continue;
  if (code.toLowerCase() === "code") continue; // header row
  const dotted = dot(code);
  if (seen.has(dotted)) continue;
  seen.add(dotted);
  entries.push({ system: "ICD10", code: dotted, description: desc });
}

// Emit a .ts module that holds the data as a JSON *string* parsed at runtime.
// Importing a 71k-element .json makes tsc infer a giant tuple type (slow / OOM);
// a single string literal is typed as `string`, so typecheck stays instant.
const jsonString = JSON.stringify(entries);
const ts =
  `// AUTO-GENERATED by scripts/build-icd.mjs from the public ICD-10-CM set\n` +
  `// (k4m1113/ICD-10-CSV). Public data, no PHI. Do not edit by hand.\n` +
  `// Stored as a JSON string + parsed at runtime so the TS compiler treats it as a\n` +
  `// single \`string\` (no ${entries.length}-element tuple inference).\n` +
  `const RAW = ${JSON.stringify(jsonString)};\n` +
  `export const ICD10_FULL: { system: string; code: string; description: string }[] = JSON.parse(RAW);\n`;
writeFileSync(outPath, ts);
console.log(`wrote ${entries.length} ICD-10-CM codes -> ${outPath}`);
